# Generated by Django 5.0.6 on 2024-07-05 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='status',
            field=models.CharField(default='active', max_length=10),
        ),
    ]
