# Generated by Django 5.0.6 on 2024-07-11 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HM1', '0003_remove_alert_status_alert_is_resolved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='source',
            field=models.CharField(choices=[('HM1', 'HM1'), ('HM2', 'HM2')], default='HM1', max_length=3),
            preserve_default=False,
        ),
    ]
