# Generated by Django 5.0.6 on 2024-07-11 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HM2', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert',
            new_name='Alert2',
        ),
    ]
