# Generated by Django 5.0.6 on 2024-07-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HM2', '0002_rename_alert_alert2'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Alert2',
            new_name='Alert',
        ),
    ]
