# Generated by Django 5.0.6 on 2024-07-09 05:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_type', models.CharField(choices=[('NVR', 'NVR'), ('DVR', 'DVR'), ('CAMERA', 'Camera')], max_length=10)),
                ('is_online', models.BooleanField(default=False)),
                ('health_status', models.CharField(default='Unknown', max_length=100)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_online', models.BooleanField(default=False)),
                ('last_heartbeat', models.DateTimeField(auto_now_add=True)),
                ('nvr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='info.device')),
            ],
        ),
    ]
